require("dotenv").config();
const moment = require("moment");
const { GoogleSpreadsheet } = require("google-spreadsheet");
const { JWT } = require("google-auth-library");

const PRIVATE_KEY = process.env.PRIVATE_KEY;
const CLIENT_EMAIL = process.env.CLIENT_EMAIL;
const SHEET_ID = process.env.SHEET_ID;
class CRUD {
  constructor(nameSheet) {
    this.nameSheet = nameSheet;
    this.doc = null;
  }

  /**
   * @param {any} nameSheet
   */
  set nameSheetTitle(nameSheet) {
    this.nameSheet = nameSheet;
  }
  async loadInfo() {
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: CLIENT_EMAIL,
      key: PRIVATE_KEY.split(String.raw`\n`).join("\n"),
      scopes: ["https://www.googleapis.com/auth/spreadsheets"],
    });
    const doc = new GoogleSpreadsheet(SHEET_ID, serviceAccountAuth);
    await doc.loadInfo();
    this.doc = doc;
  }
  async create(values, nameSheet = null) {
    if (!nameSheet) nameSheet = this.nameSheet;
    await this.loadInfo();
    const sheet = this.doc.sheetsByTitle[nameSheet];
    if (!Array.isArray(values)) {
      values = [values];
    }
    sheet.addRows(values);
  }
}
module.exports = { CRUD };
